apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: centos-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: centos-bootc
    app.kubernetes.io/part-of: centos-bootc
  name: centos-bootc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: centos-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: centos-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/centos-bootc@sha256:63419aa43004ba9a192ee69ee5943aac15a2c9938d7220822719e9ce32d33571
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
