apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: centos-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: centos-bootc
    app.kubernetes.io/part-of: centos-bootc
  name: centos-bootc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: centos-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: centos-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/centos-bootc@sha256:71f2394b48ac649ba514877a1cc5487bbb5103a7f377a4fdd40c0001187dda8c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
