apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/fedora-bootc@sha256:5ec33ca7ebac83e757b2fa8bb21f239fbea5306ab64f24b5aa91bb7d05f25185
        name: container-image
        resources: {}
status: {}
