apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: centos-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/centos-bootc@sha256:76af1f232eda80b3ec8a73af404484f3f28311fe595e1a58beed0e1177aff4b2
        name: container-image
        resources: {}
status: {}
