apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: centos-bootc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/centos-bootc@sha256:91bf1bead5c1bab1c8d391819085b5871c54d63c40045aa3015ea5483166da3e
        name: container-image
        resources: {}
status: {}
