apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: centos-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/centos-bootc@sha256:89e6b65b225854d0fad383e49f6ba12c03911f4512d14fe1d49dda8247959599
        name: container-image
        resources: {}
status: {}
