apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: centos-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/centos-bootc/centos-bootc@sha256:5bcf9ffd4e5fc33d3650416a8198b703c923f1d448fd5282d8ffc713a535d765
        name: container-image
        resources: {}
status: {}
